### ISSUE TITLE
Highlight active submenu item

### ISSUE THREAD

**Issue by purag** [purag/purag.github.io#1]
Apply the `active` class to active submenu items. For a submenu item, "active" means the top of the section is in the top half of the viewport.

### TODO

- [x]  add a `js` rule to the gulpfile
- [x]  add `_src/js/nav.coffee`
- [ ]  clean up js files in the `clean` rule

**Comment by purag** [comment]
1c612ad and 1d1ad64 fix this partially. `getClientBoundingRect()` is returning the incorrect bounds though, so the submenu items get activated too early. Will try [this](http://stackoverflow.com/questions/28966678/getboundingclientrect-returning-wrong-results) out soon.

**Comment by purag** [comment]
jQuery uses the same method (`getBoundingClientRect()` with `window.pageYOffset`/`window.scrollY` added to the result) to get the element's top bound, so I'm closing this since the problem seems out of my control.

Note: still didn't try explicitly accounting for margins and padding; may try that at some point. For now, offset information is correct enough.

**Comment by purag** [comment]
jQuery uses the same method (`getBoundingClientRect()` with `window.pageYOffset`/`window.scrollY` added to the result) to get the element's top bound, so I'm closing this since the problem seems out of my control.

Note: still didn't try explicitly accounting for margins and padding; may try that at some point. For now, offset information is correct enough.
